# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contracts Quality Test

on:
  push:
    branches: [ main, oz-audit ]
  pull_request:
    branches: [ main, oz-audit ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Compile contracts
      env:
        MORALIS_ID: ${{ secrets.MORALIS_ID }}
        DEV1_PRIVATE_KEY: ${{ secrets.DEV1_PRIVATE_KEY }}
      run: |
        npx hardhat compile
    - name: Unit tests
      env:
        MORALIS_ID: ${{ secrets.MORALIS_ID }}
        DEV1_PRIVATE_KEY: ${{ secrets.DEV1_PRIVATE_KEY }}
      run: cd hardhat && npx hardhat test
